# Experimental AArch64 Debian Linux view for Scarlet.

[[layers]]
kind = "archive"
url = "https://github.com/petitstrawberry/scarlet-bundle-debian/releases/download/v0.3.25/rootfs-aarch64-base-v0.3.25.tar.zst"
sha256 = "sha256:91c5cbf6af65a9fc8b353b26ceacb94271bd93031462ed49d1d0e4b70fa35ded"
format = "tar-zst"
strip_components = 1
to = "/systems/linux-aarch64"
